version: 2.1
orbs:
  docker: circleci/docker@1.0.1
  aws-cli: circleci/aws-cli@1.0.0
maven: &maven
  working_directory: ~/project
  docker:
    - image: maven:3.6-openjdk-8
jobs:
  package:
    docker:
      - image: maven:3.6-openjdk-8
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_DB_PASSWORD
          MYSQL_DATABASE: $MYSQL_DB_DATABASE
          MYSQL_USER: $MYSQL_DB_USER
          MYSQL_PASSWORD: $MYSQL_DB_PASSWORD      
    steps:
      - checkout
      - run:
          name: sleep
          command: sleep 10
      - run:
          name: ls
          command: ls
      - run:
          name: Build jar and test
          command: mvn package
      - persist_to_workspace:
          root: ~/project
          paths: .
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker      
      - docker/check
      - attach_workspace:
          at: ~/project
      - docker/build:
          image: marteoma/pizzas-back
          tag: "latest"
      - docker/push:
          image: marteoma/pizzas-back
          tag: "latest"
  update:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: Update service
          command: aws ecs update-service --cluster backend-pizzas-cluster --service pizzasback --force-new-deployment > /dev/null
workflows:
  version: 2
  deploy:
    jobs:
      - package
      - build:
          requires:
            - package
      - update:
          requires:
            - build